version: "3"
services:
  nginx:
    container_name: ${NGINX_CONTAINER_NAME}
    image: ${NGINX_IMAGE}:${NGINX_TAG}
    ports:
      - ${NGINX_HTTP_HOST_PORT}:80
    command: /usr/sbin/nginx -g "daemon off;"
    volumes:
      - ${PROJECT_DIR}:/www/:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    networks:
      - default

  mysql:
    container_name: ${MYSQL_CONTAINER_NAME}
    image: ${MYSQL_IMAGE}:${MYSQL_TAG}
    ports:
      - ${MYSQL_HOST_PORT}:3306
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${MYSQL_DATA_DIR}:/var/lib/mysql/:rw
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    restart: always
    networks:
      - default

  redis:
    container_name: ${REDIS_CONTAINER_NAME}
    image: ${REDIS_IMAGE}:${REDIS_TAG}
    ports:
      - ${REDIS_HOST_PORT}:6379
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    networks:
      - default

  rabbitmq:
    container_name: ${RABBIT_CONTAINER_NAME}
    image: ${RABBIT_IMAGE}:${RABBIT_TAG}
    ports:
      - ${RABBIT_AMQP_PORT}:5672
      - ${RABBIT_HTTP_PORT}:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_ROOT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_ROOT_PASSWORD}
    volumes:
      - ${RABBIT_DATA_DIR}:/var/lib/rabbitmq
    restart: always
    networks:
      - default

  pulsar:
    container_name: ${PULSAR_CONTAINER_NAME}
    image: ${PULSAR_IMAGE}:${PULSAR_TAG}
    ports:
      - ${PULSAR_PORT}:6650
      - ${PULSAR_HTTP_PORT}:8080
    environment:
      PULSAR_MEM: " -Xms512m -Xmx1024m -XX:MaxDirectMemorySize=2g"
    volumes:
      - ${PULSAR_DATA_DIR}:/pulsar/data
      - ${PULSAR_CONF_DIR}:/pulsar/conf
    command: /bin/bash -c "bin/pulsar standalone"
    restart: always
    networks:
      - default

  pulsar-dashboard:
    container_name: dev-pulsar-dashboard
    image: apachepulsar/pulsar-dashboard
    depends_on:
      - pulsar
    ports:
      - "8081:80"
    environment:
      - SERVICE_URL=http://pulsar:${PULSAR_HTTP_PORT}
    networks:
      - default

  #  zookeeper:
  #    container_name: ${ZOOKEEPER_CONTAINER_NAME}
  #    image: ${ZOOKEEPER_IMAGE}
  #    volumes:
  #      - ${ZOOKEEPER_DATA_DIR}:/data
  #    ports:
  #      - ${ZOOKEEPER_HOST_PORT}:${ZOOKEEPER_HOST_PORT}
  #
  #  kafka:
  #    container_name: ${KAFKA_CONTAINER_NAME}
  #    image: ${KAFKA_IMAGE}
  #    ports:
  #      - ${KAFKA_HOST_PORT}:${KAFKA_HOST_PORT}
  #    environment:
  #      KAFKA_BROKER_ID: 0
  #      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_ADVERTISED_LISTENERS}:${KAFKA_HOST_PORT}
  #      KAFKA_CREATE_TOPICS: "dev:2:0"
  #      KAFKA_ZOOKEEPER_CONNECT: ${ZOOKEEPER_CONTAINER_NAME}:${ZOOKEEPER_HOST_PORT}
  #      KAFKA_LISTENERS: PLAINTEXT://${KAFKA_LISTENERS}:${KAFKA_HOST_PORT}
  #    volumes:
  #      - ${KAFKA_LOG_DIR}:/kafka
  #    depends_on:
  #      - zookeeper

networks:
  default:
